spring:
  config:
    activate:
      on-profile: dev
  application:
    name: forum
  datasource:
    url: "jdbc:mysql://localhost:3306/forum?
    serverTimezone=Asia/Shanghai&
    useUnicode=true&
    characterEncoding=UTF-8"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  web:
    resources:
      static-locations: file:${forum.upload.image-path},classpath:/static/

forum:
  page:
    topic-page-size: 10
    comment-page-size: 6
  upload:
    image-path: /Users/lixin/Downloads/forum/img
  default-face: "default.jpeg"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /forum
    session:
      persistent: false
logging:
  config: classpath:log4j2.xml
